[package]
name = "treasury"
version = "0.1.0"
description = "Hypha DAO 2 Treasury Contract"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.28.0"
solana-program = "1.14.17"
