[package]
name = "membership"
version = "0.1.0"
description = "Hypha DAO 2 Membership Contract"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"

[dependencies]
anchor-lang = "0.28.0"
solana-program = "1.14.17"